require: rubocop-rails

AllCops:
  TargetRailsVersion: 6.1
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 120 # Default: 80
  Exclude:
    - db/migrate/*.rb

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented # Default: aligned

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation # Default: with_first_parameter

Metrics/AbcSize:
  Max: 45 # Default: 15
  Exclude:
    - db/migrate/*.rb

Metrics/CyclomaticComplexity:
  Max: 12 # default 7

Metrics/PerceivedComplexity:
  Max: 12 # default 8

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 25 # Default: 10
  Exclude:
    - '**/migrate/*.rb'

Metrics/ClassLength:
  Exclude:
    - '**/migrate/*.rb'

Naming/FileName:
  Exclude:
    - lib/switchman-inst-jobs.rb
    - spec/gemfiles/*.gemfile

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Style/Documentation:
  # This cop checks for missing top-level documentation of classes and modules.
  # Classes with no body and namespace modules are exempt from the check.
  # Namespace modules are modules that have nothing in their bodies except
  # classes or other modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Exclude:
    - '**/migrate/*.rb'
