dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - spec/gemfiles/rails-5.2.gemfile
  - spec/gemfiles/rails-6.0.gemfile

addons:
  postgresql: '9.6'

before_install: gem update bundler
bundler_args: --jobs 3
install: bundle install --jobs 3

script:
  - bash -c "if [ '$TRAVIS_RUBY_VERSION' = '2.5' ] && [[ '$BUNDLE_GEMFILE' == *'rails-5.2'* ]]; then bundle exec rubocop --fail-level autocorrect; fi"
  - bundle exec rake db:create db:migrate
  - bundle exec rake spec
  - bundle exec rake db:drop
