version: '2'

services:

  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      RAILS_ENV: test
    links:
      - postgres
    logging:
      options:
        max-file: '5'
        max-size: 1m

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      options:
        max-file: '5'
        max-size: 1m

  pgweb:
    image: sosedoff/pgweb
    command: [/usr/bin/pgweb, --bind=0.0.0.0, --ssl=disable, --host=postgres, --db=test, --user=postgres]
    links: [postgres]
