test:
  adapter: postgresql
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 1
  timeout: 5000
  username: <%= ENV.fetch('DB_USERNAME', '') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  host: <%= ENV.fetch('DB_HOST', '') %>
  shard_name: public
